Anonymous-forum/Models/Comments.cs
using System.ComponentModel.DataAnnotations;

namespace AnonymousForum.Models
{
    public class Comments
    {
        [Key]
        public int CommentId { get; set; }
        public string? CommentText { get; set; }
        public int ThreadId { get; set; }
    }
}

Anonymous-forum/Controllers/CommentController.cs
using Anonymous_forum.Data;
using Anonymous_forum.Models;
using Microsoft.AspNetCore.Mvc;

namespace Anonymous_forum.Controllers
{
    public class CommentController : Controller
    {
        private readonly ForumContext _dbContext;
        public CommentController(ForumContext dbContext)
        {
            _dbContext = dbContext;
        }

        public IActionResult Index()
        {
            return View();
        }
    }
}

Anonymous-forum/Controllers/ThreadController.cs
using Anonymous_forum.Data;
using Anonymous_forum.Models;
using Anonymous_forum.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace Anonymous_forum.Controllers
{
    public class ThreadController : Controller
    {
        private readonly ForumContext _dbContext;
        public ThreadController(ForumContext dbContext)
        {
            _dbContext = dbContext;
        }

        [HttpGet]
        public IActionResult Index(int id)
        {
            var result = _dbContext.Threads.Where(x => x.CategoryId == id).ToList();
            var viewModel = new DisplayCategoryThreadsViewModel { CategoryId = id, ThreadsList = result };

            return View(viewModel);
        }

        [HttpGet]
        public IActionResult CreateThread(int categoryId)
        {
            var viewModel = new CreateThreadViewModel { CategoryId = categoryId };
            return View(viewModel);
        }

        [HttpPost]
        public IActionResult PostThread(int categoryId, string threadText, string threadTitle)
        {
            if (!string.IsNullOrEmpty(threadText) && !string.IsNullOrEmpty(threadTitle))
            {
                var thread = new Threads
                {
                    CategoryId = categoryId,
                    ThreadText = threadText,
                    ThreadTitle = threadTitle
                };
                _dbContext.Threads.Add(thread);
                _dbContext.SaveChanges();
            }

            return Redirect($"~/Thread/Index/{categoryId}");
        }

        [HttpGet]
        public IActionResult Thread(int id)
        {
            var result = _dbContext.Comments.Where(x => x.ThreadId == id).ToList();
            var viewModel = new ThreadViewModel { ThreadId = id, Comments = result };

            return View(viewModel);
        }

        [HttpGet]
        public IActionResult CreateComment(int threadId)
        {
            var viewModel = new CreateCommentViewModel { ThreadId = threadId };
            return View(viewModel);
        }

        [HttpPost]
        public IActionResult PostComment(int threadId, string commentText)
        {
            if (!string.IsNullOrEmpty(commentText))
            {
                var comment = new Comments
                {
                    ThreadId = threadId,
                    CommentText = commentText
                };
                _dbContext.Comments.Add(comment);
                _dbContext.SaveChanges();
            }

            return Redirect($"~/Thread/Thread/{threadId}");
        }
    }
}

Anonymous-forum/Controllers/ThreadsController.cs
using AnonymousForum.Data;
using AnonymousForum.Models;
using AnonymousForum.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace AnonymousForum.Controllers
{
    public class ThreadsController : Controller
    {
        private readonly ForumContext _dbContext;
        public ThreadsController(ForumContext dbContext)
        {
            _dbContext = dbContext;
        }

        [HttpGet]
        public IActionResult Index(int id)
        {
            var result = _dbContext.Threads.Where(x => x.CategoryId == id).ToList();
            var viewModel = new DisplayCategoryThreadsViewModel { CategoryId = id, ThreadsList = result };

            return View(viewModel);
        }

        [HttpGet]
        public IActionResult CreateThread(int categoryId)
        {
            var viewModel = new CreateThreadViewModel { CategoryId = categoryId };
            return View(viewModel);
        }

        [HttpPost]
        public IActionResult PostThread(int categoryId, string threadText, string threadTitle)
        {
            if (!string.IsNullOrEmpty(threadText) && !string.IsNullOrEmpty(threadTitle))
            {
                var thread = new Threads
                {
                    CategoryId = categoryId,
                    ThreadText = threadText,
                    ThreadTitle = threadTitle
                };
                _dbContext.Threads.Add(thread);
                _dbContext.SaveChanges();
            }

            return Redirect($"~/Threads/Index/{categoryId}");
        }

        [HttpGet]
        public IActionResult Thread(int id)
        {
            var comments = _dbContext.Comments.Where(x => x.ThreadId == id).ToList();
            var thread = _dbContext.Threads.Where(x =>x.ThreadId == id).FirstOrDefault();
            var viewModel = new ThreadViewModel 
            {
                ThreadId = id,
                CategoryId = thread?.CategoryId ?? 0,
                Comments = comments,
                ThreadTitle = thread?.ThreadTitle,
                ThreadText = thread?.ThreadText
            };

            return View(viewModel);
        }

        [HttpGet]
        public IActionResult CreateComment(int threadId)
        {
            var viewModel = new CreateCommentViewModel { ThreadId = threadId };
            return View(viewModel);
        }

        [HttpPost]
        public IActionResult PostComment(int threadId, string commentText)
        {
            if (!string.IsNullOrEmpty(commentText))
            {
                var comment = new Comments
                {
                    ThreadId = threadId,
                    CommentText = commentText
                };
                _dbContext.Comments.Add(comment);
                _dbContext.SaveChanges();
            }

            return Redirect($"~/Threads/Thread/{threadId}");
        }
    }
}

Anonymous-forum/Views/Shared/_Card.cshtml
@model Threads?

<tr>
    <td>
        @Html.DisplayFor(modelThread => Model.ThreadTitle)
    </td>
    <td>
        @Html.ActionLink("Visit Thread", "Thread", new { id=Model.ThreadId })
    </td>
</tr>

Anonymous-forum/Views/Shared/_Comments.cshtml
@model Comments?

<tr>
    <td>
        @Html.DisplayFor(modelThread => Model.CommentText)
    </td>
</tr>

Anonymous-forum/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AnonymousForum</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AnonymousForum.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AnonymousForum</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Threads" asp-action="Index" asp-route-id="1">Education</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Threads" asp-action="Index" asp-route-id="2">Sports</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Threads" asp-action="Index" asp-route-id="3">Movies</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - AnonymousForum - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>